### ISSUE TITLE
System.ArgumentException: The value ... is not of type "BlazingPizza.Pizza" and cannot be used in this generic collection

### ISSUE THREAD

**Issue by dutts** [dotnet-presentations/blazor-workshop#335]
Been following the workshop from Step 0 and all working fine until I got to [03-show-order-status](https://github.com/dotnet-presentations/blazor-workshop/blob/main/docs/03-show-order-status.md) and when I click the `Order` button at the bottom of the sidebar I get the following exception.

This also happens when opening the solution at the step 3 save point directly. Similar to [this issue](https://github.com/dotnet-presentations/blazor-workshop/issues/315) I am also unable to debug any of the projects in this solution, but I don't think we are hitting the OrdersController anyway as the exception appears to be in the deserialisation of the Pizza json.

```
Executing endpoint 'BlazingPizza.Server.OrdersController.PlaceOrder (BlazingPizza.Server)'
Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executing endpoint 'BlazingPizza.Server.OrdersController.PlaceOrder (BlazingPizza.Server)'
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "PlaceOrder", controller = "Orders", page = "", area = ""}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.ActionResult`1[System.Int32]] PlaceOrder(BlazingPizza.Order) on controller BlazingPizza.Server.OrdersController (BlazingPizza.Server).
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Information: Route matched with {action = "PlaceOrder", controller = "Orders", page = "", area = ""}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.ActionResult`1[System.Int32]] PlaceOrder(BlazingPizza.Order) on controller BlazingPizza.Server.OrdersController (BlazingPizza.Server).
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action BlazingPizza.Server.OrdersController.PlaceOrder (BlazingPizza.Server) in 20.6231ms
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker: Information: Executed action BlazingPizza.Server.OrdersController.PlaceOrder (BlazingPizza.Server) in 20.6231ms
[40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'BlazingPizza.Server.OrdersController.PlaceOrder (BlazingPizza.Server)'
Microsoft.AspNetCore.Routing.EndpointMiddleware: Information: Executed endpoint 'BlazingPizza.Server.OrdersController.PlaceOrder (BlazingPizza.Server)'
Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/6.0.3/System.Diagnostics.StackTrace.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/6.0.3/System.Reflection.Metadata.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/6.0.3/System.IO.Compression.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
[41m[30mfail[39m[22m[49m: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.ArgumentException: The value "{"id":0,"orderId":0,"special":{"id":3,"name":"Classic pepperoni","basePrice":10.5,"description":"It\u0027s the pizza you grew up with, but Blazing hot!","imageUrl":"img/pizzas/pepperoni.jpg"},"specialId":3,"size":12,"toppings":[]}" is not of type "BlazingPizza.Pizza" and cannot be used in this generic collection. (Parameter 'value')
         at System.Collections.Generic.List`1.System.Collections.IList.Add(Object item)
         at System.Text.Json.Serialization.Converters.IListConverter`1.Add(Object& value, ReadStack& state)
         at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
         at System.Text.Json.Serialization.Converters.JsonMetadataServicesConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
         at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
         at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
         at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
         at System.Text.Json.Serialization.Converters.JsonMetadataServicesConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
         at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
         at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
         at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
         at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonConverter converter, JsonSerializerOptions options)
         at System.Text.Json.JsonSerializer.ReadAllAsync[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
         at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonInputFormatter.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)
         at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder.BindModelAsync(ModelBindingContext bindingContext)
         at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value, Object container)
         at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Duende.IdentityServer.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events, IIssuerNameService issuerNameService, IBackChannelLogoutService backChannelLogoutService) in /_/src/IdentityServer/Hosting/IdentityServerMiddleware.cs:line 102
         at Duende.IdentityServer.Hosting.MutualTlsEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes) in /_/src/IdentityServer/Hosting/MutualTlsEndpointMiddleware.cs:line 94
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Duende.IdentityServer.Hosting.DynamicProviders.DynamicSchemeAuthenticationMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/DynamicProviders/DynamicSchemes/DynamicSchemeAuthenticationMiddleware.cs:line 47
         at Duende.IdentityServer.Hosting.BaseUrlMiddleware.Invoke(HttpContext context) in /_/src/IdentityServer/Hosting/BaseUrlMiddleware.cs:line 31
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware: Error: An unhandled exception has occurred while executing the request.
```

I'm running:

Visual Studio for Mac 17.0 Preview (17.0 build 5186)
macOS 12.3.1

**Comment by dutts** [comment]
To update on this, VS Code 1.66.1 and Rider 2021.3.4 work fine, so I suspect this is a VS Mac Preview issue but will leave this here in case anyone else experiences it and finds a solution.

**Comment by Gobbenobber** [comment]
Just want to join the list of people with a similar issue; I have been able to successfully follow the tutorial until this exact point, and when clicking the "Order" button, I get a (less detailed) error in the console.
I am using JetBrains Rider (latest version) and I am unable to debug the server code, for some reason.
Everything has worked just fine until til point.
I've tried deleting the three db-related files and let it re-seed from scratch, but with no success.
I have also tried logging the JSON that is sent to the server, and it appears to be valid JSON at least, There might be some model validation that I haven't been able to figure out, though.
Anyway, simply getting error code 400 from the server and I cannot hit my breakpoints.
I realize you might not be able to support this since I am using Rider and not VS.
Also, I just want to add that simply starting the tutorial from save-point 4 works just fine! Really curious to find out what the issue is - I have not changed the Order model myself or made other changes to other models...

**Comment by Gobbenobber** [comment]
Just wanted to add that running the server from terminal (`cd BlazingPizza.Server/ && dotnet watch run`) also results in the same behavior:

```
info: Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware[10]
      No CORS policy found for the specified request.
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'BlazingPizza.Server.OrdersController.PlaceOrder (BlazingPizza.Server)'
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "PlaceOrder", controller = "Orders", page = "", area = ""}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.ActionResult`1[System.Int32]] PlaceOrder(BlazingPizza.Order) on controller BlazingPizza.Server.OrdersController (BlazingPizza.Server).
info: Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor[1]
      Executing BadRequestObjectResult, writing value of type 'Microsoft.AspNetCore.Mvc.ValidationProblemDetails'.
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action BlazingPizza.Server.OrdersController.PlaceOrder (BlazingPizza.Server) in 37.5142ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'BlazingPizza.Server.OrdersController.PlaceOrder (BlazingPizza.Server)'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 POST https://localhost:5001/orders application/json;+charset=utf-8 451 - 400 - application/problem+json;+charset=utf-8 62.4918ms
```
