### ISSUE TITLE
Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]    Unhandled exception in circuit 

### ISSUE THREAD

**Issue by Parsifal9209** [dotnet-presentations/blazor-workshop#351]
Hello, I have created 2 components, in the first component I call a method on button click, in which I display the Dialog component. Locally everything works, such an error falls in the docker container.

<MudIconButton Color="Color.Info" Size="Size.Small" Icon="@Icons.Material.Filled.Edit" OnClick="_ => EditType(context)"></MudIconButton>

Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
   Unhandled exception in circuit 'RfHtrpnKSwn7OdL53AZI3hjJJhTIdcgCwkubC8k2fgA'.
      System.ObjectDisposedException: Cannot access a disposed object.
       at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.ThrowObjectDisposedException()
        at Microsoft.AspNetCore.Components.RenderTree.ArrayBuilder`1.GrowBuffer(Int32 desiredCapacity)
      at Microsoft.AspNetCore.Components.RenderTree.RenderTreeFrameArrayBuilder.AppendElement(Int32 sequence, String elementName)
        at Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder.OpenElement(Int32 sequence, String elementName)
     at MudBlazor.MudInput`1.BuildRenderTree(RenderTreeBuilder __builder)
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)

 Why everything works locally, but not in the docker, I noticed that if you wait a long time, the error may not fall.

project:blazor server 
blazor: net6.0
mudblazor: 6.0.14

**Comment by ylr-research** [comment]
Have you open this issue to MudBlazor? It looks to me a problem in their library disposing the component.

**Comment by Parsifal9209** [comment]
@ylr-research Hello, maybe yes, could you redirect my message to them?

**Comment by ylr-research** [comment]
You should be able to file the issue here https://github.com/MudBlazor/MudBlazor
